= Arbeidssammendrag


== Metadata


TemplateId:: arbeidssammendrag


Archetype:: openEHR-EHR-EVALUATION.occupation_summary.v1




:toc:




== Arbeidssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Arbeidssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.occupation_summary.v1_
|at0004| 0..1| DV_CODED_TEXT | Arbeidsstatus
a|
* I arbeid (no.arbeidsstatus: 1)
* Ikke i arbeid (no.arbeidsstatus: 2)
* Alderspensjonist (no.arbeidsstatus: 3)
* Under utdanning/studerer (no.arbeidsstatus: 4)
* Ukjent (no.arbeidsstatus: 9)


For eksempel: "Inntektsgivende arbeid", "Arbeidsledig", "Pensjonist". Koding med en terminologi er ønskelig, der det er mulig, for eksempel OID 8150 (Volven.no). Detaljene om hver enkel jobb/ rolle kan registreres i arketypen CLUSTER.occupation_record (Arbeidsforhold/rolle).
|at0006| 0..1| DV_TEXT | Kommentar
a|
|at0009| 0..1| DV_DATE_TIME | Sist oppdatert
|


Ved implementering av arketypen forutsettes det at dersom en arbeidsepisode legges til eller oppdateres, vil også denne datoen oppdateres.
|====