= Sosialt nettverk


== Metadata


TemplateId:: sosialt_nettverk


Archetype:: openEHR-EHR-EVALUATION.social_network.v1




:toc:




== Sosialt nettverk
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Sosialt nettverk* + 
EVALUATION: _openEHR-EHR-EVALUATION.social_network.v1_
|at0002| 0..1| DV_CODED_TEXT | Samlivsstatus
a|
* Ugift/enslig (no.samlivsstatus: 1)
* Gift/samboer/registrert partner (no.samlivsstatus: 2)
* Enke/enkemann/gjenlevende partner eller samboer (no.samlivsstatus: 3)
* Skilt/separert (no.samlivsstatus: 4)
* Ukjent (no.samlivsstatus: 9)


Det anbefales å kode sivilstatus med en terminologi dersom mulig. Det er stor variasjon i verdisett som benyttes på tvers av jurisdiksjoner. Det finnes lokale, myndighetspålagte verdisett eller terminologier som for eksempel SNOMED CT eller lignende. For eksempel Ugift, Gift, Registrert partner, Samboer, Skilt, Enke, Enkemann, Enslig.
|at0018| 0..1| DV_TEXT | Kommentar
a|
|at0011| 0..1| DV_DATE_TIME | Sist oppdatert
|


Det antas at det ved implementasjon legges til rette for at denne datoen bli oppdatert dersom en tilknyttet "Person"- eller "Organisasjons"- arketype legges til eller oppdateres.
|====