= Utdanningssammendrag


== Metadata


TemplateId:: utdanningssammendrag


Archetype:: openEHR-EHR-EVALUATION.education_summary.v1




:toc:




== Utdanningssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Utdanningssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.education_summary.v1_
|at0002| 0..1| DV_CODED_TEXT | Høyeste fullførte utdanningsnivå
a|
* Ingen utdanning (no.utdanningsnivaa: 0)
* Grunnskole (no.utdanningsnivaa: 1)
* Videregående (no.utdanningsnivaa: 2)
* Universitet/Høyskole <4 år (no.utdanningsnivaa: 3)
* Universitet/Høyskole ≥4 år (no.utdanningsnivaa: 4)
* Ukjent (no.utdanningsnivaa: 9)


Koding av "Høyeste fullførte utdanningsnivå" med en terminologi er anbefalt der det er mulig. For eksempel med NUS 2000 eller Unescos ISCED klassifikasjon. Sistnevnte forefinnes ikke på norsk, men eksempel er "'Upper secondary vocational education"; "Post-secondary non-tertiary vocational education"; "Bachelor’s or equivalent level, professional"; "Doctoral or equivalent level, academic"; "Post-secondary non-tertiary vocational education"; or "Never attended an educational program".
|at0007| 0..1| DV_TEXT | Kommentar
a|
|at0028| 0..1| DV_DATE_TIME | Sist oppdatert
|


Ved implementering av arketypen forutsettes det at dersom en utdanning eller opplæring legges til eller oppdateres i CLUSTER.education_record (Utdanning), vil også denne datoen oppdateres.
|====